[package]
name = "loi-filter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
description = "Syscall filter DSL for loi"

[dependencies]
loi-core.workspace = true
globset.workspace = true
thiserror.workspace = true

[lints]
workspace = true
